### ISSUE TITLE
Fix estimateGas intermittent error if value = total balance

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/telos-evm-rpc#10]
## Description

Currenly Telos intermitently gives an error when trying to estimateGas for a transaction with value equal to the total balance of the user. Sepolia, estimates gas successfully.

This is the raw response from the Telos RPC:

```
JavaScript Object Notation: application/json
    Object
        Member Key: jsonrpc
            String value: 2.0
            Key: jsonrpc
        Member Key: id
            Number value: 48
            Key: id
        Member Key: error
            Object
                Member Key: code
                    Number value: 3
                    Key: code
                Member Key: message
                    String value: Cannot read properties of undefined (reading 'output')
                    Key: message
            Key: error
```

Fixes include fixes to telos.evm as well as fixing error handling in this repo.

## Tasks

- [ ] Fix error handling

## Linked

- [ ] [Raw action finds wrong user balance or transaction value ](https://github.com/telosnetwork/telos.evm/issues/128)
- [ ] [Estimate gas should not check for balance](https://github.com/telosnetwork/telos.evm/issues/127)
